// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAHQiS4-vMvPySGWx60z9m3P5bsJxnII',
    appId: '1:49824168278:web:1bd3da9e0099e3e77f3ef7',
    messagingSenderId: '49824168278',
    projectId: 'taskmanagement-dd7f0',
    authDomain: 'taskmanagement-dd7f0.firebaseapp.com',
    storageBucket: 'taskmanagement-dd7f0.appspot.com',
    measurementId: 'G-ERS52DLY4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_257_rUTsO05sdAZIrO3_lBs-5EdKysI',
    appId: '1:49824168278:android:83463270484287127f3ef7',
    messagingSenderId: '49824168278',
    projectId: 'taskmanagement-dd7f0',
    storageBucket: 'taskmanagement-dd7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9SeEFv35piK1LZspYyYyu8GdnYYyA38',
    appId: '1:49824168278:ios:c6e2e2deb63bd8a07f3ef7',
    messagingSenderId: '49824168278',
    projectId: 'taskmanagement-dd7f0',
    storageBucket: 'taskmanagement-dd7f0.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9SeEFv35piK1LZspYyYyu8GdnYYyA38',
    appId: '1:49824168278:ios:f99db151639873fa7f3ef7',
    messagingSenderId: '49824168278',
    projectId: 'taskmanagement-dd7f0',
    storageBucket: 'taskmanagement-dd7f0.appspot.com',
    iosBundleId: 'com.example.taskManagement.RunnerTests',
  );
}
